version_source: config # "config" or "git"
current:
  major: 2
  minor: 5
  patch: 3
  format: "{$major}.{$minor}.{$patch}"
cache:
  enabled: true
  key: pragmarx-version
build:
  mode: git-local # "number", "git-local" or "git-remote"
  number: 701031
  length: 6
  increment_by: 1
git:
  local: "git rev-parse --verify HEAD"
  remote: "git ls-remote {$repository} refs/heads/master"
  repository: "{{ env('VERSION_GIT_REMOTE_REPOSITORY') }}"
  version:
    command: "git describe"
    matcher: "/[V|v]*[ersion]*\\s*\\.*(\\d+)\\.(\\d+)\\.(\\d+)\\.*(\\w*)/"
format:
  version: "{$major}.{$minor}.{$patch} (build {$build})"
  full: "v. {{'format.version'}}"
  compact: "v{$major}.{$minor}.{$patch}-{$build}"
  ## add as many formats as you need !!!!
